# Tools used by the shell and Git configuration in this repo.
brew "bat"
brew "colordiff"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tree"
brew "uv"
brew "yazi"
brew "zoxide"

cask "font-symbols-only-nerd-font"
