add_newline = true
command_timeout = 10000

[gcloud]
disabled = true

[directory]
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "
truncation_length = 30

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
deleted = "✘${count}"

[nodejs]
symbol = " "
detect_files = ["package.json", ".nvmrc"]

[python]
symbol = " "
detect_files = ["requirements.txt", "pyproject.toml", "setup.py", ".python-version"]
pyenv_version_name = false

[conda]
symbol = " "
ignore_base = true

[cmd_duration]
min_time = 2000
format = "took [$duration](yellow) "

[time]
disabled = true
format = "[$time](dimmed white) "
time_format = "%H:%M"
